doc/General documentation edits
pyansys/pypim pull request #58
Opened 2022-05-25 19:30 UTC by PipKat

@plule-ansys I changed from "Integration Guide" to simply "Integration" because it seemed odd to call something a guide that was only a single topic. I wasn't sure if it was possible to link from the README.rst file to the Integration topic since this file is repurposed. If it can be made a link and you know how, I'd love it to work that way. I'll leave some other questions/comments for you in comments. Thanks!

2022-05-25 19:38 UTC, PipKat commented on doc/source/integration.rst
> +   is still advised.
I was trying to avoid the "down down" slang.

2022-05-25 19:39 UTC, PipKat commented on src/ansys/platform/instancemanagement/__init__.py
> +        ``True`` when the environment is configured to use PyPIM, ``False`` otherwise.
I'm hoping that this missing space is what is causing the odd rendering in the documentation.

2022-05-25 19:40 UTC, PipKat commented on src/ansys/platform/instancemanagement/definition.py
> +        If the product exposes a gRPC API, the service name begins with "grpc".
I think my changes are correct, assuming the name given is like in Aeneid.

2022-05-25 19:54 UTC, PipKat commented
@plule-ansys Did you want me to add PyPIM to the list of public repositories listed here: https://docs.pyansys.com/? That was my understanding based on Tuesday's team meeting.

2022-06-01 10:55 UTC, plule-ansys requested changes
Thanks for all the improvements

2022-06-01 15:17 UTC, PipKat commented on src/ansys/platform/instancemanagement/instance.py
> +        If the instance exposes a gRPC API, the name begins with "grpc".
```suggestion
        If the instance exposes a gRPC API, it is named "grpc".
```

2022-06-01 15:17 UTC, PipKat commented on src/ansys/platform/instancemanagement/instance.py
> +        If the instance exposes a REST-like API, the name begins with "http".
```suggestion
        If the instance exposes a REST-like API, it is named "http".
```

2022-06-01 19:43 UTC, PipKat commented on src/ansys/platform/instancemanagement/definition.py
> +        If the product exposes a REST-like API, the service name begins with "http".
```suggestion
        If the product exposes a REST-like API, the service is named "http".
```

2022-06-01 19:44 UTC, PipKat commented on src/ansys/platform/instancemanagement/definition.py
> +        If the product exposes a gRPC API, the service name begins with "grpc".
```suggestion
        If the product exposes a gRPC API, the service is named "grpc".
```

2022-06-01 20:04 UTC, PipKat commented on README.rst
> +:ref:`integration topic`<integration>.
```suggestion
:ref:`integration` topic.
```

2022-06-01 20:10 UTC, PipKat commented on README.rst
> +:ref:`integration` topic.
```suggestion
instance in a suitable environment. This process is described in the
:ref:`integration` topic.
```

2022-06-02 07:12 UTC, plule-ansys approved these changes

2022-06-02 07:12 UTC, plule-ansys commented on README.rst
> +:ref:`integration` topic.
```suggestion
integration topic.
```

Unfortunately this syntax is not valid for pypi, only for sphinx, and this file is used for both. Removing the link

2022-06-02 07:55 UTC, merged